blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('newpost/', views.newpost_view, name='newpost')
]

tested_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator




class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=500, validators=[MinLengthValidator(30)])
    author = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add = True)



    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog import models


class postform(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'author']

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from blog import forms
from django.contrib.auth.decorators import login_required

def home_view(request):
    posts = Post.objects.all().order_by('timestamp')
    return render(request, 'blog/posts.html', {'posts':posts})

@login_required()
def newpost_view(request):
    if request.method == 'POST':
        form = forms.postform(request.POST)
        if form.is_valid():
            #save t # DEBUG:
            form.save()
            return redirect('blog:home')

    else:
        form = forms.postform()
    return render(request, 'blog/newpost.html', {'form':form})

blog/templates/blog/newpost.html
{%extends 'base.html'%}

{% block content%}
<h1>we see yo</h1>
<div class="new-post">
  <div class="post">
      <h2>Create new Post</h2>
    <form class="post-form" action="{% url 'blog:newpost'%}" method="post">
      {%csrf_token%}
      {{form}}
      <input type="submit" name="Post" value="Create Post">
    </form>

  </div>
</div>
{%endblock%}

blog/templates/blog/posts.html
{%extends 'base.html'%}

{% block content%}
  <h3><a href="{% url 'blog:newpost'%}">Add Post</a></h3>

<div class="posts">
  {%for post in posts%}
    <div class="post">
        <h2><a href="#">{{post.title}}</a></h2>
        <p>{{post.body}}</p>
        <p class="time">{{post.timestamp}}</p>

    </div>

  {%endfor%}
</div>
{%endblock%}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

  </head>
  <body>
    <h1>Free Post</h1>
    <p>Speak your mind</p>
    <div class="wrapper">
      {% block content%}
      {%endblock%}
    </div>

  </body>
</html>